name: galaxy
description: Galaxy app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  dots_indicator: ^0.0.5
  youtube_player: ^3.5.0
  youtube_player_flutter: ^4.1.0
  flutter_colorpicker: ^0.2.6
  firebase_core: ^0.4.0+8  # add dependency for Firebase Core
  firebase_database: ^3.0.5
  firebase_auth: ^0.14.0+2
  flutter_facebook_login: 2.0.1
  json_serializable: 3.1.0
  google_sign_in: ^4.0.6
  http: 0.12.0+2  
  flutter_bloc: ^0.20.0
  page_indicator: ^0.2.0
  equatable: ^0.3.0
  toast: 0.1.4
  flutter_svg: ^0.14.0
  shared_preferences: ^0.5.3+4
  json_table: ^1.0.1
  connectivity: ^0.4.3+7
  flutter:
    sdk: flutter
  


 
  



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
  assets:
    - assets/images/
    